.TH JPEGINFO 1 "06 Jan 2023"
.UC 4 
.SH NAME 
jpeginfo \- prints
information and tests integrity of JPEG/JFIF files.  

.SH SYNOPSIS 
.B jpeginfo 
[ 
.B options 
] [ 
.B filenames 
] 

.SH DESCRIPTION 
.I jpeginfo
is used to generate informative listings of jpeg files, and
also to check jpeg files for errors. Program also supports automatic
deletion of broken jpegs.

.SS Default Format
.PP
Default output format:

<filename> <image_width> x <image_height> <colordepth> <image_type> <progresive_vs_normal> <size>

Example:
.PP
.RS 0
IMG_6387.jpeg 4032 x 3024 24bit JFIF  N 2416729
.RS 0
IMG_6806.jpeg 4032 x 3024 24bit Exif  N 2510587
.RS 0

.SS Extra information format
.PP
Additional information can be displayed using
.I -i
option:

<filename> <image_width> x <image_height> <colordepth> <image_type> <progresive_vs_normal> <additonal_info> <size>

Example:
.PP
.RS 0
IMG_6387.jpeg 4032 x 3024 24bit JFIF  Normal Huffman 2416729
.RS 0
IMG_6806.jpeg 4032 x 3024 24bit Exif  Normal Huffman 2510587
.RS 0
.RE

.SS Ls command style output format
.PP
Option
.I -l
moves filename to be last column, resulting output that is bit like output from `ls -l` command:

<image_width> x <image_height> <colordepth> <image_type> <progresive_vs_normal> <size> <filename>

Example:

.PP
.RS 0
4032 x 3024 24bit JFIF  N 2416729 IMG_6387.jpeg
.RS 0
4032 x 3024 24bit Exif  N 2510587 IMG_6806.jpeg 
.RS 0


.SH OPTIONS
.PP
Options may be either the traditional POSIX one letter options, or the
GNU style long options.  POSIX style options start with a single
``\-'', while GNU long options start with ``\-\^\-''.

Options offered by
.I jpeginfo
are the following:
.TP 0.6i
.B -c, --check
Check files also for errors. (default is just to read the headers).
.TP 0.6i
.B -C, --comments
Display file comments (from COM markers).
.TP 0.6i
.B -d, --delete
Delete files that have errors. (default is not to delete any files).
.TP 0.6i
.B -f<filename>, --file<filename>
Read filenames to process from given file. To use standard input (stdin)
use '-' as a filename. This is alternative to default where filenames
are given as parameters to the program.
.TP 0.6i
.B -h, --help
Display short usage information and exits.
.TP 0.6i
.B -H, --header
Display column names header in output.
.TP 0.6i
.B -2, --sha256
Calculates SHA-256 checksum for each file.
.TP 0.6i
.B --sha512
Calculates SHA-512 checksum for each file.
.TP 0.6i
.B -5, --md5
Calculates MD5 checksum for each file. 
.TP 0.6i
.B -i, --info
Displays even more information about each picture. Prints image coding 
(Huffman/Arithmetic), density (in dpi/dpc), and whether CCIR601 sampling 
was used or not.
.TP 0.6i
.B -j, --json
JavaScript Object Notation (JSON) output format.
.TP 0.6i
.B -l, --lsstyle
Uses alternate listing format (ls -l style).
.TP 0.6i
.B -v, --verbose
Enables verbose mode (positively chatty).
.TP 0.6i
.B --version
Displays program version.
.TP 0.6i
.B -q, --quiet
Quiet mode, output just the jpeg infos.
.TP 0.6i
.B -s, --csv
Comma separated values (CSV) output format.
.TP 0.6i
.B -m<mode>, --mode=<mode>
Sets the delete mode, meaningful only when used with 
.I
-d
flag. 
.I Mode
can be one of the following:
.RS
.TP
.B all
Files containing any type of errors/warnings, not necessary preventing
the decoding. (default)
.TP
.B erronly
Only files with serious errors (ie. cannot be decoded at all).
.RE
.TP 0.6i
.B -, --stdin
Read input from standard input (instead of a file).


.SH BUGS
None, so far :-)

.SH "SEE ALSO" 
jpegoptim(1)

.SH AUTHOR
Timo Kokkonen (tjko@iki.fi)

.SH COPYING
Copyright (C) 1995-2023  Timo Kokkonen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
